{% set name = "expiringdict" %}
{% set version = "1.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3fe447714f3f5c9a9e3c5fb9e8980027fd69a0f0fa305238fd284cfc74088365

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - expiringdict

about:
  home: https://github.com/mailgun/expiringdict
  license: Apache 2
  license_file: LICENSE
  license_family: APACHE
  summary: Dictionary with auto-expiring values for caching purposes

extra:
  recipe-maintainers:
    - nehaljwani
