{% set name = "expiringdict" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fe2ba427220425c3c8a3d29f6d2e2985bcee323f8bcd4021e68ebefbd90d8250

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - expiringdict

about:
  home: https://github.com/mailgun/expiringdict
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE
  summary: Dictionary with auto-expiring values for caching purposes

extra:
  recipe-maintainers:
    - nehaljwani
